name: Cloud AUD

plugins:
  - name: vyper
  - name: polygon
  - name: geth

default_ecosystem: ethereum

ethereum:
  goerli:
    default_provider: geth
  mainnet:
    default_provider: geth

polygon:
  mainnet:
    default_provider: geth

geth:
  ethereum:
    goerli:
      uri: https://rpc.ankr.com/eth_goerli
    mainnet:
      uri: https://rpc.ankr.com/eth

  polygon:
    mainnet:
      uri: https://rpc.ankr.com/polygon
    mumbai:
      uri: https://rpc.ankr.com/polygon_mumbai
