name: Cloud AUD

plugins:
  - name: vyper
  - name: polygon

default_ecosystem: ethereum

ethereum:
  ropsten:
    default_provider: geth
  rinkeby:
    default_provider: geth
  goerli:
    default_provider: geth
  mainnet:
    default_provider: geth

polygon:
  mainnet:
    default_provider: geth

geth:
  ethereum:
    ropsten:
      uri: https://rpc.ankr.com/eth_ropsten
    rinkeby:
      uri: https://rpc.ankr.com/eth_rinkeby
    goerli:
      uri: https://rpc.ankr.com/eth_goerli
    mainnet:
      uri: https://rpc.ankr.com/eth

  polygon:
    mainnet:
      uri: https://rpc.ankr.com/polygon
    mumbai:
      uri: https://rpc.ankr.com/polygon_mumbai
